# 配置文件

# win翻墙客户端下载 https://github.com/shadowsocksrr/shadowsocksr-csharp/releases/download/4.9.2/ShadowsocksR-win-4.9.2.zip

title = "视频采集器"
appid = ""

dbFile = "./db_cache"    #本地存储目录，记录下载过的视频，忽略

# txt 文件保存的视频信息 标题和描述的长度限制
title_length = 30
desc_lenth = 350

# 视频存放目录，可以为空
output = ""
# 定时采集 每隔几小时采集一次
task = 0

# 是否使用ssr ,如果机器能访问外网，就不用ssr,能否访问外网看的是socket5(终端)，而不是http(网页)
ssr = true

# 视频过滤
[condition]
    width = 500      # 最小宽度
    height = 300     # 最小高度
    direction = "h"  # v: 竖版视频  h： 横版视频
    resolution = "720p" #指定分辨率  240p 360p 480p 720p 1080p
    size = [5,100]   # 视频大小范围 单位：M
    black_list = ["华农兄弟","李子柒","抖音"] #标题中含有这些字样，过滤

[youtube]
    switch = true
    keywords = ["娱乐", "搞笑","影视"] #根据关键词下载自己需要的视频
    duration_limit = [1, 4]  # 时长范围限制 单位：分钟,超出限制不下载
    time_limit = 3 # 视频发布时间限制 1（今天内）, 2（本周内）, 3（本月内）, 4(本年内)
    count = 100  #单个关键词下载数量
    pages = ["https://www.youtube.com/channel/UCz6nsRgmASX_zSV7fGwGmVw/videos"] #采集自定义页面
    urls = ["https://www.youtube.com/watch?v=Ap0huJwyT7g"]
