# 配置文件

title = "视频采集器"
appid = "ab09f0a5a268d599a706b1bcd321965b"


dbFile = "./db_cache"    #本地存储目录，记录下载过的视频，忽略
proxy = "127.0.0.1:1086"  # 免费账户自己填写socks5代理地址


title_length = 30
desc_lenth = 350

# 视频存放目录，可以为空
output = ""

# 视频过滤
[condition]
    width = 500      # 最小宽度
    height = 300     # 最小高度
    direction = "h"  # v: 竖版视频  h： 横版视频
    size = [5,100]   # 视频大小范围 单位：M
    similarity = 0.5 # 视频相似度过滤(忽略)
    black_list = ["华农兄弟","李子柒"] #标题中含有这些字样，过滤
    filter = ["t"]

[zy]
    switch = false
    cookie = "aliyungf_tc=AQAAAHtCl0+LAggALI70ctZO+UPzsFK8"
    token = "T9K9NKOaZ14_QhiQ7KpL9TpjEQZ11-o3ah29pE1pxfFF02c44QaotybsuAQWIqinSBe5U"

    [zy.favor]  #收藏
    group = ["素材"]
    enable = true
    limit = 20

    [zy.attention]  #关注
    enable = true
    limit = -1

    [zy.recommend]  #推荐
    enable = true
    limit = -1

[youtube]
    switch = true
    keywords = ["娱乐搞笑", "八卦新闻","影视剪辑"] #根据关键词下载自己需要的视频
    duration_limit = 5  # 时长限制 单位：分钟,超出限制不下载
    time_limit = 3 # 视频发布时间限制 1（今天内）, 2（本周内）, 3（本月内）, 4(本年内)
    count = 100  #单个关键词下载数量